- hosts: localhost
  gather_facts = no

  vars:
    docker_id: shk230
    docker_key: "{{ lookup('env', 'DOCKER_KEY') }}"
    image_name: "{{ docker_id }}/goorm-myweb"

  tasks:
  - block:
    - name: Login to Docker Hub
      docker_login:
        username: "{{ docker_id }}"
        password: "{{ docker_key }}"
        state: present
    - name: Image Build with WAR
      docker_image:
        build:
          path: .
          rm: yes
        name: "{{ image_name }}"
        push: yes
        source: build
    always:
    - name: Logout to Docker Hub
      docker_login:
        username: shk230
        state: absent
