- hosts: localhost
  gather_facts: no

  vars:
    docker_id: shk230
    docker_key: "{{ lookup('env', 'DOCKER_KEY') }}"
    image_name: "{{ docker_id }}/goorm-myweb"

  tasks:
  - block:  
    - name: Remove existing image
      docker_image:
        name: "{{ image_name }}"
        source: local
        state: absent

    - name: Image build with war
      docker_image:
        build:
          path: .
          rm: yes
        name: "{{ image_name }}"
        source: build
        force_source: yes
