- hosts: localhost
  gather_facts = no

  tasks:
  - block:
    - name: Login to Docker Hub
      docker_login:
        username: shk230
        password: "{{ lookup('env','DOCKER_KEY') }}"
        state: present
    - name: Image Build with WAR
      docker_image:
        build:
          path: .
          rm: yes
        name: "{{ image_name }}"
        push: yes
        source: build
    - name: Create/Start Container
        docker_container:
          name: "{{ container_name }}"
          image: "{{ image_name }}"
          exposed_ports:
            - "8080:8080"
          pull: yes
          recreate: yes
          state: started
    always:
    - name: Logout to Docker Hub
      docker_login:
        username: shk230
        state: absent
